#!/usr/bin/env python3


include: "rules/common.smk"
include: "rules/samtools_import.smk"
include: "rules/ncbi_dl.smk"


# include: "rules/samtools_fasta.smk"


# this is from the bpa_dataportal_downloads project
# results of a search for query = {"sample_id": '102.100.100/411655'}
data_file_dict = {
    "350768_AusARG_BRF_HCN7WDRXY_S3_L002_R1_001.fastq.gz": "https://data.bioplatforms.com/dataset/bpa-ausarg-hi-c-350768-hcn7wdrxy/resource/62eb9891ef16f3f1a4272bbe627b66c1/download/350768_AusARG_BRF_HCN7WDRXY_S3_L002_R1_001.fastq.gz",
    "350768_AusARG_BRF_HCN7WDRXY_S3_L002_R2_001.fastq.gz": "https://data.bioplatforms.com/dataset/bpa-ausarg-hi-c-350768-hcn7wdrxy/resource/2e5bf004e6a4b60484f760a92cb30fb6/download/350768_AusARG_BRF_HCN7WDRXY_S3_L002_R2_001.fastq.gz",
    "350768_AusARG_BRF_HCN7WDRXY_S3_L001_R1_001.fastq.gz": "https://data.bioplatforms.com/dataset/bpa-ausarg-hi-c-350768-hcn7wdrxy/resource/b55411e6c637bc3513a15e59c8e21c4c/download/350768_AusARG_BRF_HCN7WDRXY_S3_L001_R1_001.fastq.gz",
    "350768_AusARG_BRF_HCN7WDRXY_S3_L001_R2_001.fastq.gz": "https://data.bioplatforms.com/dataset/bpa-ausarg-hi-c-350768-hcn7wdrxy/resource/9587a0c1b1f66de712682f888b6a2fa5/download/350768_AusARG_BRF_HCN7WDRXY_S3_L001_R2_001.fastq.gz",
}



rule format_config_file:
    input:
        sanger_config_template=local(sanger_config_template),
    output:
        rendered_yaml=Path(
            "resources", "config", "sangertol_genomeassembly_params.yaml"
        ),
    params:
        pacbio_reads=[rules.ncbi_dl_target.output.reads],
        hic_reads=[rules.samtools_import.output.cram],
    container:
        get_container("ncbi-datasets-pylib")
    script:
        "scripts/format_config_file.py"


rule config_target:
    default_target: True
    localrule: True
    input:
        rules.samtools_import.output,
        rules.ncbi_dl_target.output,
        rendered_yaml=rules.format_config_file.output.rendered_yaml,
    output:
        "results/sangertol_genomeassembly_params.yaml",
    shell:
        "cp {input.rendered_yaml} {output}"


module test_rm:
    snakefile:
        github("tomharrop/test-module-rm", path="workflow/Snakefile", tag="v0.0.6")
    config:
        {
            **config,
            "query_genome": storage.s3(
                (
                    "s3://pawsey1132.atol.testassembly/"
                    "ThemedaTriandra106636/results/sanger_tol/"
                    "ThemedaTriandra106636.hifiasm-hic.v3/scaffolding_hap1/"
                    "yahs/out.break.yahs/hap1_scaffolds_final.fa"
                ),
            ),
        }


use rule * from test_rm as test_rm_*


use rule clean from test_rm as test_rm_clean with:
    resources:
        runtime=lambda wildcards, attempt: 720 * attempt,
        mem_mb=lambda wildcards, attempt: 48e3 * attempt,


use rule all from test_rm as rm_all with:
    output:
        storage.s3(
            "s3://pawsey1132.atol.testassembly/ThemedaTriandra106636/results/out_scaffolds_final.masked.fa.gz",
        ),
