#!/usr/bin/env python3


include: "rules/common.smk"
include: "rules/samtools_fasta.smk"


# this is from the bpa_dataportal_downloads project
# results of a search for query = {"sample_id": '102.100.100/411655'}
data_file_dict = {
    "395386_PP_AGRF_m84073_230802_055109_s2.ccs.bam": "https://data.bioplatforms.com/dataset/bpa-pp-pacbio-hifi-395386-m84073_230802_055109_s2/resource/688d158c73f4bb40293581860e8ef3e8/download/395386_PP_AGRF_m84073_230802_055109_s2.ccs.bam",
}


rule format_config_file:
    input:
        sanger_config_template=local(sanger_config_template),
    output:
        rendered_yaml=add_bucket_to_path(
            Path(
                dataset_id, "results", "config", "sangertol_genomeassembly_params.yaml"
            )
        ),
    params:
        pacbio_reads=[rules.samtools_fasta.output.reads],
    container:
        get_container("ncbi-datasets-pylib")
    script:
        "scripts/format_config_file.py"


rule config_target:
    default_target: True
    localrule: True
    input:
        storage.s3(rules.samtools_fasta.output),
        rendered_yaml=storage.s3(rules.format_config_file.output.rendered_yaml),
    output:
        "results/sangertol_genomeassembly_params.yaml",
    shell:
        "cp {input.rendered_yaml} {output}"

